server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    name: test  #数据库名
    url: jdbc:mysql://mydev:3306/spring_demo #url
    username: root  #用户名
    password: iZ2zej4i2jdf3ovg1qxejxZ  #密码
    driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动

mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  type-aliases-package: org.zjp.spring.bean #配置实体类